server:
  port: 8132
spring:
  datasource:
    # 数据源配置
    # 使用H2数据库
#    url: jdbc:h2:~/test
    #tcp可配置多个来源
#    url: jdbc:h2:tcp://localhost/~/test
    #file单个，速度快
    url: jdbc:h2:file:D:/h2db/test
    driver-class-name: org.h2.Driver
    username: admin
    password: 123456

  #    schema: classpath:db/schema.sql
  #    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    # 配置h2的远程访问
    console:
      #，进行该配置，你就可以通过YOUR_URL/h2-console访问h2 web consloe。YOUR_URL是你程序的访问URl如http://localhost:8132/
      path: /h2-console
      # 配置程序开启时就会启动h2 web consloe
      enabled: true